import {chromium} from 'playwright-core';
import {createServer} from 'node:http';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import assert from 'node:assert/strict';
import {Store} from '../src/config/store.js';
import {admin} from '../src/server/admin.js';
const dir=await mkdtemp(tmpdir()+'/coach-browser-');
const provider=createServer(async(req,res)=>{for await(const _ of req){}res.setHeader('Content-Type','text/event-stream');res.end('data: '+JSON.stringify({id:'qa',choices:[{index:0,delta:{role:'assistant',content:'Synthetic QA response: choose an easy walk today, prioritize sleep, and reassess soreness tomorrow. This is a transport fixture, not live model inference.'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({id:'qa',choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n');});
await new Promise<void>(r=>provider.listen(0,'127.0.0.1',r));
const store=new Store(dir);await store.init();const app=await admin(store,0);
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(app.origin);await page.locator('#adminKey').fill(store.secrets.admin);await page.locator('#unlock').click();await page.locator('#studio').waitFor({state:'visible'});await page.locator('#baseUrl').fill(`http://127.0.0.1:${(provider.address() as any).port}/v1`);await page.locator('#model').fill('synthetic-qa');await page.locator('#apiKey').fill('synthetic-qa-key');await page.locator('#name').fill('Sage');await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#notice')?.textContent?.startsWith('Saved.'));await page.locator('#previewButton').click();await page.waitForFunction(()=>document.querySelector('#notice')?.textContent?.startsWith('Preview complete'));assert.match(await page.locator('#answer').innerText(),/Synthetic QA response/);assert.match(await page.locator('#prompt').textContent()??'',/name: Sage/);assert.equal(store.publicConfig().persona.name,'Sage');assert.equal(await page.locator('#apiKey').inputValue(),'');await mkdir('docs/evidence',{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'docs/evidence/studio-desktop.png'});await page.locator('#preview').scrollIntoViewIfNeeded();await page.screenshot({path:'docs/evidence/studio-preview.png'});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'docs/evidence/studio-mobile.png'});assert.deepEqual(errors,[]);console.log('Browser PASS: unlock, config persistence, actual Pi + synthetic HTTP preview, cleared secret inputs, desktop/mobile no overflow; 0 page errors.');await page.close();}finally{await browser.close();await app.close();provider.closeAllConnections();await new Promise(r=>provider.close(r));await rm(dir,{recursive:true,force:true});}
